# dependabot.yml 的一个简单配置
version: 2
updates:
  # 1. 检查 Go 模块 (go.mod)
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "weekly"
    reviewers:
      - "fun7257"
    assignees:
      - "fun7257"

  # 2. 检查 GitHub Actions (CI/CD 工作流)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "fun7257"
    assignees:
      - "fun7257"