name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to build (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # Add this line to grant write permissions for contents
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag_name || github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Download Go modules
      run: |
        go mod tidy
        go mod download

    - name: Build
      env:
        GOOS: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o sgv

    - name: Archive production artifacts
      run: |
        tar -czvf sgv-${{ matrix.os }}-${{ matrix.arch }}.tar.gz sgv

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      with:
        files: sgv-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
        tag_name: ${{ github.event.inputs.tag_name || github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
